FP 0.38 add Signal scoring
ooni/pipeline pull request #344
Opened 2021-04-29 11:09 UTC by FedericoCeratto

2021-04-29 15:09 UTC, hellais requested changes
It should use the signal_backend_status and failure keys to determine the blocking, not just the values of the tcp_connect test results as the experiment is also checking if the TLS certificate is good.

2021-04-29 15:09 UTC, hellais commented on af/fastpath/fastpath/core.py
> +    return scores
You should be reading the keys:
```
{
    "signal_backend_failure": "FAILURE STRING",
    "signal_backend_status": "blocked"
}
```
See: https://github.com/ooni/spec/blob/master/nettests/ts-029-signal.md

2021-04-30 14:24 UTC, FedericoCeratto commented on af/fastpath/fastpath/core.py
> +    return scores
Done

2021-05-05 10:25 UTC, hellais approved these changes
LGTM

2021-05-05 11:37 UTC, merged